import { storage } from "./storage";
import type { InsertClient } from "@shared/schema";

const defaultSchedule = {
  mon: { enabled: true, start: "08:00", end: "16:00" },
  tue: { enabled: true, start: "08:00", end: "16:00" },
  wed: { enabled: true, start: "08:00", end: "16:00" },
  thu: { enabled: true, start: "08:00", end: "16:00" },
  fri: { enabled: true, start: "08:00", end: "16:00" },
};

const CLIENTS_DATA: InsertClient[] = [
  {
    name: "JADW",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    homeAddress: "123 filler filler",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: false,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: false,
    allowSplits: false,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: false,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "JAZW",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    homeAddress: "1234 filler",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: false,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: false,
    allowSplits: false,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: false,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "KIOW",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: false,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: true,
    allowSplits: true,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: true,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "JISL",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: true,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: true,
    allowSplits: true,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "half",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: true,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "CAPY",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: false,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: true,
    allowSub: false,
    allowSplits: false,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: false,
    trainingStyle: "double",
    canBeGrouped: false,
    allowedLunchPeerIds: [],
    allowGroupsOf3: false,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "ELLL",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "home",
    homeAddress: "456 Home Street",
    driveTimeMinutes: 30,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: false,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: true,
    allowSplits: false,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: false,
    allowedLunchPeerIds: [],
    allowGroupsOf3: false,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "ANTO",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: true,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: true,
    allowSplits: true,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: true,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "ELRA",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: false,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: false,
    allowSplits: false,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: false,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "MACB",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: true,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: true,
    allowSplits: true,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: true,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "NOEY",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: false,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: false,
    allowSplits: false,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: false,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  },
  {
    name: "SERE",
    active: true,
    bcbaId: null,
    phoneNumbers: [],
    defaultLocation: "clinic",
    driveTimeMinutes: 0,
    focusStaffIds: [],
    trainedStaffIds: [],
    floatRbtsAllowed: true,
    leadRbtsAllowed: true,
    noLongerTrainedIds: [],
    excludedStaffIds: [],
    allowAllDaySameStaff: false,
    allowSub: true,
    allowSplits: true,
    allowBtPast60Days: true,
    allowBtPast6Months: true,
    allowedTrainerIds: [],
    leadSignOffAllowed: true,
    trainingStyle: "full",
    canBeGrouped: true,
    allowedLunchPeerIds: [],
    allowGroupsOf3: true,
    disallowedGroupCombos: [],
    schedule: defaultSchedule
  }
];

async function seedClients() {
  console.log("Starting client seed...");
  
  try {
    for (const client of CLIENTS_DATA) {
      await storage.createClient(client);
    }
    console.log(`✓ Seeded ${CLIENTS_DATA.length} clients`);
    console.log("✓ Client seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding clients:", error);
    process.exit(1);
  }
  
  process.exit(0);
}

seedClients();
